# Spenden für AI Paperless Organizer
# Diese Datei aktiviert den "Sponsor" Button auf GitHub

# Ko-fi
ko_fi: chriswilms

# PayPal
custom: ["https://www.paypal.com/paypalme/withmoney"]

# GitHub Sponsors (kannst du später aktivieren unter github.com/sponsors)
# github: syberx
